CREATE TABLE MEMBER
(
    SEQ         BIGINT         NOT NULL    AUTO_INCREMENT COMMENT 'PK',
    ID          VARCHAR(50)    NOT NULL    COMMENT '아이디',
    PASSWORD    VARCHAR(60)    NOT NULL    COMMENT '비밀번호',
    SIGNATURE   VARCHAR(44)    NULL        COMMENT 'JWT 시그니처',
    REG_DATE    BIGINT         NOT NULL    COMMENT '가입일',
    ACTIVATION  CHAR(1)        NOT NULL    DEFAULT 1 COMMENT '활성유무[활성:1, 비활성:0]',
    CONSTRAINT PK_MEMBER_SEQ PRIMARY KEY (SEQ)
);

CREATE TABLE DIARY
(
    SEQ            BIGINT         NOT NULL    AUTO_INCREMENT COMMENT 'PK',
    MEMBER_SEQ     VARCHAR(50)    NOT NULL    COMMENT '회원 SEQ',
    CONTENT        TEXT           NOT NULL    COMMENT '일기내용',
    REG_DATE       BIGINT         NOT NULL    COMMENT '작성일',
    ACTIVATION     CHAR(1)        NOT NULL    DEFAULT 1 COMMENT '활성유무[활성:1, 비활성:0]',
    CONSTRAINT PK_DIARY_SEQ PRIMARY KEY (SEQ)
);
